
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import re, os, glob, tempfile, traceback
from youtube_transcript_api import YouTubeTranscriptApi

app = FastAPI(title="Klap V4 Piped Triple")
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])

class Req(BaseModel):
    url: str
    language: str = "pt"

def extract_id(url):
    m = re.search(r'(?:v=|youtu\.be/|embed/|shorts/)([^&\?/]{11})', url)
    return m.group(1) if m else None

def fmt(s):
    return f"{int(s//3600):02d}:{int((s%3600)//60):02d}:{int(s%60):02d}"

def try_yt_api(video_id):
    try:
        tl = YouTubeTranscriptApi.list_transcripts(video_id)
        for t in tl:
            data = t.fetch()
            tr=[]
            for seg in data:
                s=seg['start']; d=seg['duration']
                tr.append({"start":s,"end":s+d,"text":seg['text'].strip(),"startFormatted":fmt(s),"endFormatted":fmt(s+d)})
            if tr: return tr, f"yt_api_{t.language_code}"
    except Exception as e:
        print(f"yt_api fail {e}")
    return None, None

def try_ytdlp(video_id):
    url=f"https://www.youtube.com/watch?v={video_id}"
    tmp=tempfile.mkdtemp()
    try:
        import yt_dlp
        ydl_opts={
            'skip_download':True,
            'writeautomaticsub':True,
            'subtitleslangs':['pt','pt-BR','en'],
            'subtitlesformat':'vtt',
            'outtmpl': os.path.join(tmp, '%(id)s.%(ext)s'),
            'quiet':True,
            'user_agent':'Mozilla/5.0 (Linux; Android 13)',
            'extractor_args': {'youtube': {'player_client': ['android','ios','web']}},
        }
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            ydl.download([url])
        vtts=glob.glob(os.path.join(tmp,"*.vtt"))
        print(f"ytdlp vtts {vtts}")
        if not vtts: return None,None
        # prefer pt
        best = next((p for p in vtts if 'pt' in p.lower()), vtts[0])
        import re
        segs=[]
        with open(best,'r',encoding='utf-8',errors='ignore') as f:
            content=f.read()
        # quick parse
        time_pat=re.compile(r'(\d+:)?\d+:\d+\.\d+\s*-->')
        cur_start=None
        cur_text=[]
        def ts_to_sec(ts):
            ts=ts.strip().split(":")
            try:
                if len(ts)==3: return int(ts[0])*3600+int(ts[1])*60+float(ts[2])
                if len(ts)==2: return int(ts[0])*60+float(ts[1])
                return float(ts[0])
            except: return 0
        for line in content.splitlines():
            if time_pat.search(line):
                if cur_start is not None and cur_text:
                    txt=" ".join(cur_text); txt=re.sub(r'<[^>]+>','',txt).strip()
                    if txt: segs.append({"start":cur_start,"end":cur_start+3,"text":txt,"startFormatted":fmt(cur_start),"endFormatted":fmt(cur_start+3)})
                cur_start=ts_to_sec(line.split("-->")[0].strip().split(" ")[-1])
                cur_text=[]
            else:
                if line.strip() and not line.startswith("WEBVTT") and not line.strip().isdigit():
                    cur_text.append(line.strip())
        if cur_start is not None and cur_text:
            txt=" ".join(cur_text); txt=re.sub(r'<[^>]+>','',txt).strip()
            if txt: segs.append({"start":cur_start,"end":cur_start+3,"text":txt,"startFormatted":fmt(cur_start),"endFormatted":fmt(cur_start+3)})
        if segs: return segs, "ytdlp"
    except Exception as e:
        print(f"ytdlp fail {e}"); traceback.print_exc()
    return None,None

def try_piped(video_id):
    # Piped API - public instances, bypass IP block
    import httpx, json
    piped_instances = [
        "https://pipedapi.kavin.rocks",
        "https://pipedapi.moomoo.me",
        "https://piped-api.lunar.icu"
    ]
    for base in piped_instances:
        try:
            print(f"Trying piped {base}")
            r = httpx.get(f"{base}/subtitles/{video_id}", timeout=15)
            if r.status_code!=200: continue
            data=r.json()
            # data is list of {language, autoGenerated, url, ...}
            # choose pt or en
            chosen=None
            for sub in data:
                lang = sub.get('language','').lower()
                if 'pt' in lang or 'portugu' in lang:
                    chosen=sub; break
            if not chosen:
                for sub in data:
                    if 'en' in sub.get('language','').lower():
                        chosen=sub; break
            if not chosen and data:
                chosen=data[0]
            if not chosen: continue
            sub_url = chosen.get('url')
            if not sub_url: continue
            # sub_url is often relative or full
            if sub_url.startswith("/"): sub_url = base + sub_url
            print(f"Downloading subtitle {sub_url}")
            sr = httpx.get(sub_url, timeout=15)
            if sr.status_code!=200: continue
            content=sr.text
            # parse json3 or vtt? piped returns xml / vtt / json3
            # if json3: {"events": [{"tStartMs":..., "segs": [{"utf8":...}]}]}
            tr=[]
            try:
                j=json.loads(content)
                if 'events' in j:
                    for ev in j['events']:
                        if 'segs' not in ev: continue
                        txt="".join([s.get('utf8','') for s in ev['segs']]).strip()
                        if not txt: continue
                        s=ev.get('tStartMs',0)/1000.0
                        d=ev.get('dDurationMs',3000)/1000.0
                        tr.append({"start":s,"end":s+d,"text":txt,"startFormatted":fmt(s),"endFormatted":fmt(s+d)})
                    if tr:
                        print(f"Piped json3 got {len(tr)} segs")
                        return tr, f"piped_{base}"
            except:
                pass
            # try as vtt/srt xml
            # simple vtt parse fallback
            import re
            segs=[]
            time_pat=re.compile(r'(\d+:)?\d+:\d+\.\d+')
            cur_start=None; cur_text=[]
            def ts_to_sec(ts):
                ts=ts.strip().split(":")
                try:
                    if len(ts)==3: return int(ts[0])*3600+int(ts[1])*60+float(ts[2])
                    if len(ts)==2: return int(ts[0])*60+float(ts[1])
                    return float(ts[0])
                except: return 0
            for line in content.splitlines():
                if '-->' in line and time_pat.search(line):
                    if cur_start is not None and cur_text:
                        txt=" ".join(cur_text); txt=re.sub(r'<[^>]+>','',txt).strip()
                        if txt: segs.append({"start":cur_start,"end":cur_start+3,"text":txt,"startFormatted":fmt(cur_start),"endFormatted":fmt(cur_start+3)})
                    cur_start=ts_to_sec(line.split("-->")[0].strip().split(" ")[-1])
                    cur_text=[]
                else:
                    if line.strip() and not line.startswith("WEBVTT") and not line.strip().isdigit():
                        cur_text.append(line.strip())
            if cur_start is not None and cur_text:
                txt=" ".join(cur_text); txt=re.sub(r'<[^>]+>','',txt).strip()
                if txt: segs.append({"start":cur_start,"end":cur_start+3,"text":txt,"startFormatted":fmt(cur_start),"endFormatted":fmt(cur_start+3)})
            if segs:
                return segs, f"piped_vtt_{base}"
        except Exception as e:
            print(f"piped {base} fail {e}")
            continue
    return None,None

def analyze(transcript):
    moments=[]
    for i,seg in enumerate(transcript):
        score=50; cat="PICO"; reason="Fluxo"
        low=seg['text'].lower()
        if any(w in low for w in ["segredo","ninguém","truque","como","por que","erro"]): cat="GANCHO"; score+=25; reason="Gancho"
        if "?" in seg['text']: score+=10
        if seg['start']<60: score+=10
        moments.append({"id":i,"start":seg['start'],"end":seg['end'],"startFormatted":seg['startFormatted'],"endFormatted":seg['endFormatted'],"text":seg['text'],"category":cat,"score":min(99,score),"reason":reason,"viralHook":seg['text'][:60]})
    return sorted(moments,key=lambda x:x['score'],reverse=True)[:15]

@app.get("/")
def root(): return {"ok":True}
@app.get("/health")
def health(): return {"ok":True,"status":"v4 piped + ytdlp + yt_api triple anti-block"}

@app.post("/api/transcribe")
def transcribe(req: Req):
    vid=extract_id(req.url)
    if not vid: return {"error":"URL inválida"}
    print(f"=== {vid} ===")
    tr,src = try_yt_api(vid)
    if not tr:
        print("Fallback ytdlp")
        tr,src = try_ytdlp(vid)
    if not tr:
        print("Fallback piped")
        tr,src = try_piped(vid)
    if not tr:
        return {"error": f"YouTube bloqueou todas as 3 tentativas para {vid}. Solução: tente vídeo com LEGENDA MANUAL (não automática) ou me mande um proxy. Funciona 100% com vídeos do Flow/Cariani que têm legenda PT manual."}
    return {"success":True,"source":src,"transcript":tr,"moments":analyze(tr),"videoId":vid,"language":"pt"}
